name: WD401-L5-CI-CD

# Only run the CI/CD pipeline on the main branch
on:
  push:
    branches:
      - main

# Environment variables for postgres database
# TODO: Replace with environment variables
env:
  PG_DATABASE: wd-todo-test
  PG_USER: postgres
  PG_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Start postgres database
      postgres:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wd-todo-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Code Validation
      #   run: |

      # Install dependencies
      - name: Install
        run: |
          npm ci

      # Test the application
      - name: Run Unit Tests
        run: npm test

      - name: Run DB Migrations
        run: |
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate

      - name: Start Server
        run: |
          PORT=3000 npm start &
          sleep 5

      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run

      # - name: Deploy
      #   run: |

      # - name: Report
      #   run: |
